sudo: enabled
os:
  - linux
# - osx
language: node_js
node_js:
  - "12"
  - "10"
# - '8'
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
install:
  - npm ci
script:
  - npm run lint
